# Generated by Django 6.0.4 on 2026-04-19 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_contentcategory_contenttype_delete_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentcategory',
            options={'ordering': ['name'], 'verbose_name': 'content category', 'verbose_name_plural': 'content categories'},
        ),
    ]
