# Generated by Django 6.0.4 on 2026-04-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('short_description', models.CharField(max_length=250)),
                ('full_description', models.TextField()),
                ('icon_name', models.CharField(help_text='Lucide icon name e.g. Stethoscope, BookOpen', max_length=100)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='services/covers/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
