# Generated by Django 6.0.4 on 2026-04-20 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('service_type', models.CharField(choices=[('consulting', 'Consulting Services'), ('training', 'Training Service'), ('veterinary', 'Veterinary Medical Service'), ('animal_feed', 'Animal Feed'), ('farm_products', 'Sale of Farm Products'), ('equipment', 'Animal Husbandry Equipment'), ('general', 'General Inquiry')], default='general', max_length=50)),
                ('farm_size', models.CharField(blank=True, choices=[('small', 'Small (under 1 hectare)'), ('medium', 'Medium (1-10 hectares)'), ('large', 'Large (10+ hectares)'), ('commercial', 'Commercial Farm')], max_length=50)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.CharField(choices=[('morning', 'Morning (8am - 12pm)'), ('afternoon', 'Afternoon (12pm - 5pm)'), ('any', 'Any Time')], default='any', max_length=20)),
                ('location', models.CharField(help_text='City or region in Ethiopia', max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Any additional details')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
