# Generated by Django 6.0.4 on 2026-04-20 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='+251 919 076 607', max_length=30)),
                ('email', models.EmailField(default='info@trustagroconsult.com', max_length=254)),
                ('address', models.CharField(default='Addis Ababa, Ethiopia', max_length=200)),
                ('whatsapp_number', models.CharField(default='251919076607', max_length=20)),
                ('booking_url', models.URLField(default='https://trustagroconsult.com/book-consulting')),
                ('founded_year', models.PositiveIntegerField(default=2021)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
        migrations.CreateModel(
            name='SiteStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. Trained Farmers', max_length=100)),
                ('value', models.CharField(help_text='e.g. 500+ or 3', max_length=20)),
                ('suffix', models.CharField(blank=True, default='+', help_text='Suffix shown after number e.g. + or empty', max_length=10)),
                ('icon_name', models.CharField(help_text='Lucide icon name e.g. Users', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
